/* District doors: actual destinations with browser-local activities. */
(() => {
'use strict';
const attributes=['bv','ms','ts','cc','ep','fr','hh','ne','nw','os','pk','se','sq'];
const selector=attributes.map(k=>'[data-'+k+']').join(',')+', [data-destination]';
const imageBase='games/honeybrook-craft-fair/img/';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const registry=new Map();
for(const button of document.querySelectorAll(selector)){
 const key=attributes.find(k=>button.hasAttribute('data-'+k));if(!key)continue;
 const name=button.getAttribute('data-'+key);if(name==='Return to Honeybrook')continue;registry.set(name,{name,key,source:button.closest('section')?.id,detail:button.querySelector('small')?.textContent||'',icon:button.querySelector('span')?.textContent||'🍯'});
}
const districts={'Northern Edge':'northernEdgeWorld',"Scholars' Quarter":'scholarsWorld','Harmony Hill':'harmonyWorld','Town Square':'townSquareWorld','Main Street':'mainStreetWorld','Care & Community':'careCommunityWorld','Entertainment District':'entertainmentWorld','Bridgeview':'bridgeviewWorld','Community Park':'communityParkWorld'};
// Find district sections from their doors instead of relying on legacy section naming.
for(const [name,key] of Object.entries({'Northern Edge':'ne',"Scholars' Quarter":'sq','Harmony Hill':'hh','Town Square':'ts','Main Street':'ms','Care & Community':'cc','Entertainment District':'ep','Bridgeview':'bv','Community Park':'pk'}))districts[name]=document.querySelector('[data-'+key+']')?.closest('section')?.id;
const view=document.createElement('section');view.id='destinationVisit';view.hidden=true;view.setAttribute('aria-label','Honeybrook destination');document.body.appendChild(view);
let current=null,origin=null,scroll=0,context=null,audio=null;
const storageKey='honeybrook_destination_visits_v1';let memory={};try{const value=JSON.parse(localStorage.getItem(storageKey)||'{}');if(value&&typeof value==='object'&&!Array.isArray(value))memory=value;}catch{}
function save(){try{localStorage.setItem(storageKey,JSON.stringify(memory));}catch{view.querySelector('.visit-save').textContent='Browser saving unavailable; progress lasts for this visit.';}}
function state(){const key=current.name;if(!memory[key]||typeof memory[key]!=='object')memory[key]={};return memory[key];}
function mode(name){if(/garden|farm|orchard/i.test(name))return 'garden';if(/art|paint/i.test(name))return 'art';if(/music|harmony|rehearsal|stage|listening|dance/i.test(name))return 'music';if(/post office/i.test(name))return 'mail';if(/café|bakery|cakes|kitchen/i.test(name))return 'cafe';if(/market|BEARcessities|threads/i.test(name))return 'shop';if(/health|dental|emergency|safety|wellness/i.test(name))return 'care';if(/hall|gazette|business|outreach/i.test(name))return 'board';if(/school|library|learning|technology|achievement/i.test(name))return 'learning';if(/game|arcade|lanes|golf|gym|skate|pool|sports|playground|commons/i.test(name))return 'game';return 'walk';}
function picture(m,name){if(/Hearthwell/i.test(name))return 'hearthwell-home.webp';if(/welcome|cottage|home|porch/i.test(name))return 'welcome-house.webp';return {garden:'garden.jpg',art:'paint.jpg',music:'village.jpg',mail:'harold-home.png',cafe:/cakes|bakery/i.test(name)?'bakery.jpg':'cakes.jpg',shop:'hive.jpg',care:'welcome-house.webp',board:'wood.jpg',learning:'schoolroom.webp',game:'carnival.png',walk:/pond|creek/i.test(name)?'pond.jpg':/woods|northern|pillar|tree|mushroom/i.test(name)?'hollow.jpg':'honeybrook-town-map.jpg'}[m];}
function button(label,action,extra=''){return '<button type="button" data-visit-action="'+action+'" '+extra+'>'+label+'</button>';}
function widget(m){
 if(m==='garden')return '<h2>Tend your plot</h2><p>Plant a seed, water it, then gather the ripe crop.</p><div class="visit-plots"></div><p class="visit-count"></p>';
 if(m==='art')return '<h2>Your studio easel</h2><label>Paint color <input id="visitColor" type="color" value="#9a466c"></label><canvas id="visitEasel" width="800" height="460" aria-label="Drawing easel" tabindex="0"></canvas><div class="visit-actions">'+button('Clear canvas','clear')+button('Download my painting','download')+'</div><p>Draw with a finger or mouse. Your saved picture stays in this browser.</p>';
 if(m==='music')return '<h2>Play the piano</h2><p>Choose a key or use A S D F G H J. Sound starts when you play.</p><div class="visit-piano">'+['C','D','E','F','G','A','B'].map((n,i)=>button(n,'note','data-note="'+i+'" aria-label="Play '+n+'"')).join('')+'</div><div class="visit-staff" aria-live="polite"></div>'+button('Clear my melody','clearMelody');
 if(m==='mail')return '<h2>Harold’s writing desk</h2><p>Write a pretend letter to a Honeybrook neighbor. It stays in this game.</p><form id="visitLetter"><label>To <select name="recipient"><option>Amelia</option><option>Big Mama Mary</option><option>Wally</option><option>Sammy</option></select></label><label>Your note <textarea name="message" maxlength="500" required placeholder="Dear neighbor…"></textarea></label><button>Put in the mailbag</button></form><h3>Your outgoing mailbag</h3><ul class="visit-outbox"></ul>';
 if(m==='shop')return '<h2>'+(/threads/i.test(current.name)?'Choose your outfit':'Shop shelves')+'</h2><p>Collect items in your pretend basket. No real purchases.</p><div class="visit-shelves"></div><h3>Your basket</h3><div class="visit-basket"></div>'+button('Empty basket','empty');
 if(m==='cafe')return '<h2>'+(/cakes|bakery/i.test(current.name)?'Wally’s cookie counter':'Prepare a welcome tray')+'</h2><p>Pick three ingredients, then serve your creation.</p><div class="visit-shelves">'+['🍯 Honey','🥛 Milk','🫖 Tea','🥐 Pastry','🍓 Berries'].map(x=>button(x,'ingredient','data-item="'+esc(x)+'"')).join('')+'</div><div class="visit-tray"></div>'+button('Serve my tray','serve')+'<p class="visit-count"></p>';
 if(m==='care')return '<h2>Community care station</h2><p>Help prepare this fictional clinic for its next visitor.</p><div class="visit-checklist">'+['Set out a fresh towel','Fill the water pitcher','Arrange the waiting chairs','Stock the welcome basket'].map((x,i)=>'<label><input type="checkbox" data-care-step="'+i+'"> '+x+'</label>').join('')+'</div><progress max="4" value="0"></progress><p class="visit-count"></p>';
 if(m==='board')return '<h2>'+(/business/i.test(current.name)?'Your project desk':'Community noticeboard')+'</h2><form id="visitBoard"><label>Your pretend town notice <input name="notice" maxlength="160" required placeholder="Garden picnic on Saturday…"></label><button>Pin to the board</button></form><div class="visit-notices"></div>';
 if(m==='learning')return '<h2>Professor Honeywell’s practice table</h2><p>Arrange the words to complete today’s sentence.</p><div class="visit-wordbank">'+['belongs.','bear','Every'].map(w=>button(w,'word','data-word="'+w+'"')).join('')+'</div><div class="visit-sentence"></div>'+button('Try again','resetWords')+'<p class="visit-count"></p>';
 if(m==='game')return '<h2>Catch the honey drops</h2><p>Tap the moving honey jar five times to finish a round.</p><div class="visit-game">'+button('🍯','catch','aria-label="Catch the honey jar"')+'</div><p class="visit-count"></p>'+button('New round','newRound');
 return '<h2>Explore this place</h2><p>Follow the stops on your visit. Your bear moves through the scene as you go.</p><div class="visit-trail">'+['Entrance','Lookout','Resting place'].map((x,i)=>button(x,'walk','data-stop="'+i+'"')).join('')+'</div><p class="visit-count"></p>';
}
function render(){const s=state(),m=mode(current.name);view.dataset.mode=m;view.innerHTML='<header><button type="button" data-visit-back>← Back to '+esc(current.source?document.getElementById(current.source)?.querySelector('h2')?.textContent||'town':'town')+'</button><span class="visit-save">Progress saves in this browser</span></header><main><div class="visit-heading"><p>'+esc(current.icon)+' HONEYBROOK · '+esc(current.source?document.getElementById(current.source)?.querySelector('h2')?.textContent||'YOUR VISIT':'YOUR VISIT')+'</p><h1 tabindex="-1">'+esc(current.name)+'</h1><p>'+esc(current.detail)+'</p></div><div class="visit-room"><img class="visit-room-photo" src="'+imageBase+picture(m,current.name)+'" alt="'+esc(current.name)+' setting"><img class="visit-bear" src="assets/visitor.webp" alt="Your bear"><div class="visit-live-props" aria-hidden="true"></div><span class="visit-room-sign">'+esc(current.name)+'</span></div><section class="visit-workspace">'+widget(m)+'</section><nav class="visit-neighbors" aria-label="Other places in this district"><h2>Where to next?</h2>'+[...registry.values()].filter(x=>x.key===current.key&&x.name!==current.name).map(x=>'<button data-visit-door="'+esc(x.name)+'">'+esc(x.icon)+' '+esc(x.name)+'</button>').join('')+'</nav></main>';refresh();if(m==='art')easel();view.querySelector('h1').focus();}
function refresh(){if(view.querySelector('.visit-workspace')?.dataset.venue)return;const s=state(),m=mode(current.name),count=view.querySelector('.visit-count');
 if(m==='garden'){s.plots=Array.isArray(s.plots)&&s.plots.length===6?s.plots:Array(6).fill(0);view.querySelector('.visit-plots').innerHTML=s.plots.map((p,i)=>button(['🌱 Plant seed','💧 Water sprout','🥕 Gather crop'][p]||'🌱 Plant seed','plot','data-plot="'+i+'"')).join('');count.textContent=(s.harvest||0)+' crops gathered.';view.querySelector('.visit-live-props').innerHTML=s.plots.map(p=>'<span>'+(['🟤','🌱','🥕'][p]||'🟤')+'</span>').join('');}
 if(m==='shop'){const items=/threads/i.test(current.name)?['🧥 Plum coat','🧣 Honey scarf','👒 Straw hat']:['🍎 Apples','🍯 Honey','📓 Notebook','🌷 Flowers'];view.querySelector('.visit-shelves').innerHTML=items.map(x=>button(x,'add','data-item="'+esc(x)+'"')).join('');view.querySelector('.visit-basket').textContent=(s.basket||[]).join(' · ')||'Your basket is empty.';}
 if(m==='cafe'){view.querySelector('.visit-tray').textContent=(s.tray||[]).join(' + ')||'Your serving tray is empty.';view.querySelector('[data-visit-action="serve"]').disabled=(s.tray||[]).length!==3;count.textContent=(s.served||0)+' trays served.';}
 if(m==='mail'){view.querySelector('.visit-outbox').innerHTML=(s.letters||[]).map(l=>'<li><b>To '+esc(l.recipient)+'</b><p>'+esc(l.message)+'</p></li>').join('')||'<li>No letters yet.</li>';}
 if(m==='board')view.querySelector('.visit-notices').innerHTML=(s.notices||[]).map(n=>'<article>📌 '+esc(n)+'</article>').join('')||'<p>The board is ready for your first notice.</p>';
 if(m==='music')view.querySelector('.visit-staff').textContent=(s.melody||[]).join(' ♪ ')||'Your melody will appear here.';
 if(m==='care'){const steps=s.steps||[];view.querySelectorAll('[data-care-step]').forEach(e=>e.checked=steps.includes(+e.dataset.careStep));view.querySelector('progress').value=steps.length;count.textContent=steps.length===4?'The care station is ready. Thank you!':steps.length+' of 4 preparations finished.';}
 if(m==='learning'){const words=s.words||[];view.querySelector('.visit-sentence').textContent=words.join(' ')||'Choose the first word.';view.querySelectorAll('[data-word]').forEach(b=>b.disabled=words.includes(b.dataset.word));count.textContent=words.length===3?(words.join(' ')==='Every bear belongs.'?'Correct! Every bear belongs.':'That order needs another try.') :'';}
 if(m==='game'){const n=s.catches||0;count.textContent=n>=5?'Round complete! Five honey jars caught.':n+' of 5 caught.';const b=view.querySelector('[data-visit-action="catch"]');b.disabled=n>=5;b.style.left=(8+(n*23)%70)+'%';b.style.top=(10+(n*31)%60)+'%';}
 if(m==='walk'){count.textContent=['At the entrance.','At the lookout.','Resting at the end of your visit.'][s.stop||0];view.querySelector('.visit-bear').style.left=[12,48,78][s.stop||0]+'%';view.querySelectorAll('[data-stop]').forEach(b=>b.setAttribute('aria-pressed',String(+b.dataset.stop===(s.stop||0))));}
}
function open(name,source){let place=registry.get(name);if(!place)place={name,key:'town',source,detail:'Come inside and spend some time in Honeybrook.',icon:'🍯'};if(!current){origin=document.activeElement;scroll=window.scrollY;context=[...document.body.children].filter(e=>e!==view&&e.tagName!=='SCRIPT'&&e.tagName!=='STYLE');context.forEach(e=>e.inert=true);document.body.classList.add('visit-open');dispatchEvent(new Event('honeybrook-visit-open'));}document.getElementById('welcome')?.classList.remove('active');document.getElementById('town')?.classList.add('active');current=place;view.hidden=false;window.scrollTo(0,0);render();save();}
function leave(){if(!current)return;if(audio){audio.close();audio=null;}const source=current.source;view.hidden=true;current=null;context?.forEach(e=>e.inert=false);document.body.classList.remove('visit-open');window.scrollTo(0,scroll);if(origin?.isConnected)origin.focus({preventScroll:true});else document.getElementById(source)?.scrollIntoView({block:'start'});}
function navigate(name,source){history.pushState({honeybrookVisit:true},'', '#visit='+encodeURIComponent(name));open(name,source);}
function tone(i){try{audio=audio||new(window.AudioContext||window.webkitAudioContext)();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type='triangle';o.frequency.value=[261.63,293.66,329.63,349.23,392,440,493.88][i];g.gain.setValueAtTime(.15,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.65);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+.7);}catch{}const s=state();s.melody=[...(s.melody||[]),['C','D','E','F','G','A','B'][i]].slice(-32);refresh();save();}
function easel(){const canvas=view.querySelector('#visitEasel'),ctx=canvas.getContext('2d');ctx.fillStyle='#fffaf0';ctx.fillRect(0,0,800,460);if(state().painting){const img=new Image();img.onload=()=>{if(canvas.isConnected)ctx.drawImage(img,0,0);};img.src=state().painting;}let down=false,last;const point=e=>{const r=canvas.getBoundingClientRect();return [(e.clientX-r.left)*800/r.width,(e.clientY-r.top)*460/r.height];};canvas.onpointerdown=e=>{down=true;last=point(e);canvas.setPointerCapture(e.pointerId);};canvas.onpointermove=e=>{if(!down)return;const p=point(e);ctx.strokeStyle=view.querySelector('#visitColor').value;ctx.lineWidth=6;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(...last);ctx.lineTo(...p);ctx.stroke();last=p;};const finish=()=>{if(!down)return;down=false;state().painting=canvas.toDataURL('image/png');save();};canvas.onpointerup=finish;canvas.onpointercancel=finish;}
document.addEventListener('click',e=>{
 const district=e.target.closest('[data-town-place]');if(district){const name=district.dataset.townPlace,target=document.getElementById(districts[name]);if(target){e.preventDefault();e.stopImmediatePropagation();target.scrollIntoView({behavior:'smooth',block:'start'});return;}if(name==='Welcome House'){e.preventDefault();e.stopImmediatePropagation();navigate('Welcome House');return;}}
 const door=e.target.closest(selector);if(door){e.preventDefault();e.stopImmediatePropagation();const k=attributes.find(k=>door.hasAttribute('data-'+k));let name=k?door.getAttribute('data-'+k):null;if(!name&&typeof destinations!=='undefined')name=destinations[door.dataset.district]?.[Number(door.dataset.destination)]?.[0];if(name==='Return to Honeybrook'){document.getElementById('hbPlayableWorld')?.scrollIntoView({behavior:'smooth',block:'start'});return;}if(name)navigate(name,door.closest('section')?.id);return;}
 if(!current)return;
 if(e.target.closest('[data-visit-back]')){if(history.state?.honeybrookVisit)history.back();else{history.replaceState(null,'',location.pathname+location.search);leave();}return;}
 const next=e.target.closest('[data-visit-door]');if(next){navigate(next.dataset.visitDoor);return;}
 const b=e.target.closest('[data-visit-action]');if(!b)return;const s=state(),a=b.dataset.visitAction;
 if(a==='plot'){const i=+b.dataset.plot;if(s.plots[i]===2)s.harvest=(s.harvest||0)+1;s.plots[i]=(s.plots[i]+1)%3;}
 if(a==='add')s.basket=[...(s.basket||[]),b.dataset.item].slice(-30);
 if(a==='empty')s.basket=[];
 if(a==='ingredient')s.tray=[...(s.tray||[]),b.dataset.item].slice(-3);
 if(a==='serve'&&(s.tray||[]).length===3){s.served=(s.served||0)+1;s.tray=[];}
 if(a==='word')s.words=[...(s.words||[]),b.dataset.word].slice(0,3);
 if(a==='resetWords')s.words=[];
 if(a==='catch')s.catches=Math.min(5,(s.catches||0)+1);
 if(a==='newRound')s.catches=0;
 if(a==='walk')s.stop=+b.dataset.stop;
 if(a==='note'){tone(+b.dataset.note);return;}
 if(a==='clearMelody')s.melody=[];
 if(a==='clear'){delete s.painting;render();}
 if(a==='download'){const link=document.createElement('a');link.href=view.querySelector('canvas').toDataURL('image/png');link.download='honeybrook-painting.png';link.click();}
 refresh();save();
},true);
view.addEventListener('submit',e=>{e.preventDefault();const s=state(),data=new FormData(e.target);if(e.target.id==='visitLetter')s.letters=[...(s.letters||[]),{recipient:data.get('recipient'),message:String(data.get('message')).trim()}].slice(-30);if(e.target.id==='visitBoard')s.notices=[...(s.notices||[]),String(data.get('notice')).trim()].slice(-30);e.target.reset();refresh();save();});
view.addEventListener('change',e=>{if(!e.target.matches('[data-care-step]'))return;state().steps=[...view.querySelectorAll('[data-care-step]:checked')].map(x=>+x.dataset.careStep);refresh();save();});
document.addEventListener('keydown',e=>{if(!current)return;if(e.key==='Escape'){view.querySelector('[data-visit-back]').click();return;}if(mode(current.name)==='music'&&!view.querySelector('.visit-workspace')?.dataset.venue&&!e.repeat&&!e.target.matches('input,textarea,select')){const i='asdfghj'.indexOf(e.key.toLowerCase());if(i>=0){e.preventDefault();tone(i);}}});
function route(){const match=location.hash.match(/^#visit=(.+)$/);if(match){try{open(decodeURIComponent(match[1]));}catch{leave();}}else leave();}
addEventListener('honeybrook-enter-place',event=>{const name=event.detail?.name;if(typeof name!=='string'||name.length>120)return;document.getElementById('hbWorldDialog')?.close();navigate(name);});
addEventListener('popstate',route);route();
})();
