/* Individual activities layered onto the destination view. All saves are local. */
(() => {
'use strict';
const root=document.getElementById('destinationVisit'),KEY='honeybrook_living_places_v1';let data={};try{data=JSON.parse(localStorage.getItem(KEY)||'{}');if(!data||typeof data!=='object'||Array.isArray(data))data={};}catch{}
const esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const name=()=>root.querySelector('h1')?.textContent||'';
const room=()=>{const n=name();if(!data[n]||typeof data[n]!=='object')data[n]={};return data[n];};
const save=()=>{try{localStorage.setItem(KEY,JSON.stringify(data));}catch{const e=root.querySelector('.living-status');if(e)e.textContent='Browser saving is unavailable. Keep this page open to keep your progress.';}};
const btn=(label,action,attrs='')=>'<button type="button" data-living="'+action+'" '+attrs+'>'+label+'</button>';
let mounted='',timer;
function kind(n){return /cakes|bakery/i.test(n)?'bake':/Hearthwell|Welcome House$|Country Homes/i.test(n)?'home':/garden|farm|orchard/i.test(n)?'garden':'';}
const neighbors={bake:{name:'Wally Crumbwell',image:'wally',intro:'The oven’s warm. Let’s make something we can share.',choices:[['What’s your secret?','Patience—and measuring before pouring. I learned the pouring part the messy way.'],['Who gets the first cookie?','Sammy, if he reaches the counter first. Save one for yourself, too.']]},home:{name:'Amelia Honeybrook',image:'amelia',intro:'Make yourself comfortable. A room starts feeling like home one little choice at a time.',choices:[['Can I stay a while?','Of course. You don’t have to decide everything today.'],['How did Honeybrook begin?','Tom fixed a bridge. We made room for Sammy. The rest grew from neighbors helping neighbors.']]},garden:{name:'Sammy Patchwell',image:'sammy',intro:'I’ll hold the watering can. You pick what we grow.',choices:[['What should we plant?','Carrots grow quickly. Flowers take longer, but the bees like them.'],['Will it grow while I’m away?','Once you water it, yes. We can come back and see what changed.']]},other:{name:'Harold Pawst',image:'harold',intro:'Good day. I’m making my rounds.',choices:[['Any news?','I deliver mail. Miss Patty handles the news—usually without being asked.'],['Need a helping paw?','Keep the path clear and the addresses readable. That helps more than you think.']]}};
function mount(){if(root.hidden){mounted='';clearInterval(timer);return;}const n=name(),workspace=root.querySelector('.visit-workspace');if(!workspace||mounted===n&&workspace.dataset.living)return;mounted=n;clearInterval(timer);const k=kind(n),s=room();workspace.dataset.living=k||'neighbor';
if(k==='bake'){s.phase=s.phase||'measure';s.ingredients=s.ingredients||[];workspace.innerHTML='<h2>Wally’s baking kitchen</h2><p>Measure the ingredients, mix the dough, then bake a batch of honey cookies.</p><div class="living-bake"></div><p class="living-status" role="status"></p>';}
if(k==='home'){s.decor=s.decor||{};workspace.innerHTML='<h2>Your cozy corner</h2><p>Choose what belongs in your room. Each choice appears in the room above.</p><div class="living-decor">'+[['rug','🧶 Honey rug'],['plant','🪴 Window plant'],['lamp','🛋️ Reading lamp'],['picture','🖼️ Family picture']].map(([id,label])=>btn(label,'decor','data-item="'+id+'"')).join('')+'</div><label>Wall color <select id="livingWall"><option value="plum">Warm plum</option><option value="sage">Soft sage</option><option value="honey">Honey cream</option></select></label><p class="living-status" role="status"></p>';}
if(k==='garden'){s.plots=Array.isArray(s.plots)&&s.plots.length===6?s.plots:Array.from({length:6},()=>null);workspace.innerHTML='<h2>A garden that keeps growing</h2><p>Plant, water, and come back to gather your crop. Carrots take 30 seconds after watering; flowers take one minute.</p><label>Seeds <select id="livingSeed"><option value="carrot">🥕 Carrots · 30 seconds</option><option value="flower">🌻 Flowers · 1 minute</option></select></label><div class="living-plots"></div><p class="living-status" role="status"></p>';timer=setInterval(()=>{if(!root.hidden&&name()===n)update();},1000);}
if(k==='bake'&&s.phase==='oven')timer=setInterval(update,500);
if(k){const props=document.createElement('div');props.className='living-props';root.querySelector('.visit-room').appendChild(props);if(k==='home')root.querySelector('.visit-room-photo').src='games/honeybrook-craft-fair/img/room.jpg';update();}
const person=neighbors[k]||neighbors.other,panel=document.createElement('section');panel.className='living-neighbor';panel.innerHTML='<img src="assets/'+person.image+'.webp" alt="'+person.name+'"><div><h2>'+person.name+'</h2><p>'+person.intro+'</p><div class="visit-actions">'+person.choices.map(([label],i)=>btn(label,'talk','data-choice="'+i+'"')).join('')+'</div><p class="living-reply" role="status">'+esc(s.reply||'')+'</p></div>';workspace.after(panel);
}
function update(){const k=kind(name()),s=room(),status=root.querySelector('.living-status'),props=root.querySelector('.living-props');if(!status)return;
if(k==='bake'){let html='';if(s.phase==='measure')html='<h3>1 · Measure into the bowl</h3><div class="visit-actions">'+['Flour','Butter','Honey'].map(x=>btn((s.ingredients.includes(x)?'✓ ':'')+x,'measure','data-ingredient="'+x+'" '+(s.ingredients.includes(x)?'disabled':''))).join('')+'</div>'+btn('Mix the dough','mix',s.ingredients.length===3?'':'disabled');if(s.phase==='mix')html='<h3>2 · Stir your dough</h3><progress max="5" value="'+(s.stirs||0)+'"></progress>'+btn('Stir the bowl','stir');if(s.phase==='oven')html='<h3>3 · Bake until golden</h3><p>Let the oven work its magic for five seconds.</p>'+btn('Take out the cookies','finish',Date.now()>=s.readyAt?'':'disabled');if(s.phase==='done')html='<h3>Your cookies are ready!</h3>'+btn('Share a cookie with Sammy','share',s.shared?'disabled':'')+btn('Bake another batch','again');root.querySelector('.living-bake').innerHTML=html;status.textContent=(s.batches||0)+' '+(s.batches===1?'batch':'batches')+' baked · '+(s.sharedTotal||0)+' '+(s.sharedTotal===1?'cookie':'cookies')+' shared.';props.innerHTML=s.phase==='done'?'<span class="living-cookie">🍪 🍪 🍪</span>':'<span class="living-cookie">'+(s.phase==='oven'?'🔥':'🥣')+'</span>';}
if(k==='home'){const icons={rug:'🧶',plant:'🪴',lamp:'🛋️',picture:'🖼️'};props.innerHTML=Object.keys(icons).filter(id=>s.decor[id]).map(id=>'<span class="living-'+id+'">'+icons[id]+'</span>').join('');root.querySelectorAll('[data-living="decor"]').forEach(b=>b.setAttribute('aria-pressed',String(!!s.decor[b.dataset.item])));root.querySelector('#livingWall').value=s.wall||'plum';root.querySelector('.visit-room').dataset.wall=s.wall||'plum';status.textContent=Object.values(s.decor).filter(Boolean).length+' decorations placed. Your room is saved.';}
if(k==='garden'){const now=Date.now();root.querySelector('.living-plots').innerHTML=s.plots.map((p,i)=>{const ready=p?.wateredAt&&now-p.wateredAt>=(p.crop==='flower'?60000:30000),label=!p?'🌱 Plant seed':!p.wateredAt?'💧 Water '+p.crop:ready?'🧺 Gather '+p.crop:'🌿 Growing · '+Math.ceil(((p.crop==='flower'?60000:30000)-(now-p.wateredAt))/1000)+'s';return btn(label,'plot','data-plot="'+i+'" '+(p?.wateredAt&&!ready?'disabled':''));}).join('');props.innerHTML=s.plots.map(p=>'<span>'+(!p?'🟤':!p.wateredAt?'🌱':now-p.wateredAt>=(p.crop==='flower'?60000:30000)?(p.crop==='flower'?'🌻':'🥕'):'🌿')+'</span>').join('');root.querySelector('.visit-live-props').hidden=true;status.textContent=(s.harvest||0)+' '+(s.harvest===1?'crop':'crops')+' gathered · growth continues when you leave.';}}
root.addEventListener('click',e=>{const b=e.target.closest('[data-living]');if(!b||b.disabled)return;const s=room(),a=b.dataset.living,k=kind(name());if(a==='talk'){const p=neighbors[k]||neighbors.other;s.reply=p.choices[+b.dataset.choice][1];root.querySelector('.living-reply').textContent=s.reply;save();return;}if(a==='decor')s.decor[b.dataset.item]=!s.decor[b.dataset.item];if(a==='measure'&&!s.ingredients.includes(b.dataset.ingredient))s.ingredients.push(b.dataset.ingredient);if(a==='mix'&&s.ingredients.length===3){s.phase='mix';s.stirs=0;}if(a==='stir'&&s.phase==='mix'){s.stirs++;if(s.stirs>=5){s.phase='oven';s.readyAt=Date.now()+5000;clearInterval(timer);timer=setInterval(update,500);}}if(a==='finish'&&s.phase==='oven'&&Date.now()>=s.readyAt){s.phase='done';s.batches=(s.batches||0)+1;clearInterval(timer);}if(a==='share'&&!s.shared){s.shared=true;s.sharedTotal=(s.sharedTotal||0)+1;}if(a==='again'){s.phase='measure';s.ingredients=[];s.shared=false;}if(a==='plot'){const i=+b.dataset.plot,p=s.plots[i];if(!p)s.plots[i]={crop:root.querySelector('#livingSeed').value};else if(!p.wateredAt)p.wateredAt=Date.now();else if(Date.now()-p.wateredAt>=(p.crop==='flower'?60000:30000)){s.harvest=(s.harvest||0)+1;s.plots[i]=null;}}update();save();});
root.addEventListener('change',e=>{if(e.target.id==='livingWall'){room().wall=e.target.value;update();save();}});
new MutationObserver(mount).observe(root,{childList:true,attributes:true,attributeFilter:['hidden']});mount();
})();
