/* Optional visual stories layered onto Honeybrook's existing playable scene graph. */
(()=>{
'use strict';
const world=document.querySelector('#playableWorld');
const storageKey='hb_story_memory_v1';
let memory;try{memory=JSON.parse(localStorage.getItem(storageKey)||'{}')}catch{memory={}}
if(!memory||typeof memory!=='object')memory={};
memory.witnessed=Array.isArray(memory.witnessed)?memory.witnessed:[];
memory.choices=Array.isArray(memory.choices)?memory.choices:[];
let current=null,elapsed=0,idle=0,location='',lastLine=-1,seenScene=new Set();
const motion=window.matchMedia('(prefers-reduced-motion: reduce)');
const bar=document.createElement('div');bar.className='hb-story-tools';
bar.innerHTML='<button id="hbWatch">Watch a town moment</button><button id="hbStoryStop" hidden>Return to wandering</button><button id="hbAutoScenes" aria-pressed="true">Living scenes on</button><button id="hbStoryMemory">Town memories</button><span id="hbStoryLabel">The town has its own little stories.</span>';
world.querySelector('.hb-world-tools').after(bar);
const choices=document.createElement('div');choices.className='hb-story-choices';choices.hidden=true;world.append(choices);
let autoplay=memory.autoplay!==false;
function save(){try{localStorage.setItem(storageKey,JSON.stringify({...memory,autoplay}))}catch{}}
function setDialogue(who,line){const d=world.querySelector('.pw-scene:not([hidden]) .pw-dialogue');if(!d)return;const b=document.createElement('b'),s=document.createElement('span');b.textContent=who;s.textContent=line;d.replaceChildren(b,s)}
const stories={
 bakery:{title:'Wally’s cupcake situation',duration:19,camera:650,lines:[[1,'Wally','Two dozen. That is a very sensible number.'],[6,'Wally','Unless… I doubled it twice.'],[11,'Wally','Nobody move. Especially the cupcakes.'],[16,'Wally','Please tell me somebody’s hungry.']],choices:[['Take one','Wally','One cupcake rescued. Wally beams like you solved a national crisis.'],['Ask about the recipe','Wally','“Two dozen became eight. I blame enthusiasm.”'],['Just watch','Wally','He gathers the trays. You are welcome to stay without helping.']]},
 hearthwell:{title:'The controller negotiations',duration:20,camera:560,lines:[[1,'Lance','It’s my turn!'],[5,'Landis','The game was wrong. I did NOT lose.'],[10,'Buddy','If I hear ONE more argument…'],[15,'Buddy','Both controllers belong to me now.'],[18,'Lance','…Can we at least watch?']],choices:[['Laugh with Buddy','Buddy','“This is why we have a park.”'],['Sit with the cubs','Landis','A spot opens on the sofa. The argument changes to what to watch.'],['Keep wandering','Buddy','“Come back anytime, baby.”']]},
 welcomehouse:{title:'A place for the Newberrys',duration:22,camera:530,lines:[[1,'Toby','Welcome to Honeybrook! Short tour or seventeen-hour tour?'],[6,'Papa Newberry','Actually… we’re looking for a place.'],[12,'Toby','Well, that’s convenient. We got one.'],[17,'Bella Newberry','Is that a library over there?'],[20,'Grandpa Newberry','Entirely too friendly. …Where’s the ice cream?']],choices:[['Welcome them','Papa Newberry','“It already feels a little less strange here.”'],['Point toward the library','Bella Newberry','She memorizes the route before anyone has unpacked.'],['Give them room','Toby','The family settles in at its own pace. No checklist appears.']]},
 woodsedge:{title:'Three notes at Singing Pond',duration:23,camera:640,lines:[[2,'Northern Woods','The branches shift. Jonesha stops walking.'],[7,'Jonesha','Wait. Did you hear that?'],[12,'Field observation','Three tones carry over the water. No source is visible.'],[17,'Field observation','A roof-like shape appears through the mist, then disappears.'],[21,'Jonesha','Seeing something doesn’t mean we know what it is.']],choices:[['Record what you saw','Field observation','Three tones and a distant roof-like shape observed. Source, location and identity remain unconfirmed.'],['Listen quietly','Northern Woods','The wind returns. Nobody asks you to solve anything.'],['Return to town','Jonesha','“We can come back in daylight.”']]},
 cafe:{title:'Harold’s breakfast delivery',duration:20,camera:620,lines:[[1,'Harold','Mail for the Honey Mug. Just the mail.'],[7,'Miss Patty','Sit down, honey. Coffee?'],[11,'Harold','I’m on my route.'],[15,'Miss Patty','Then this pie is on your route too.'],[18,'Harold','…That is different.']],choices:[['Ask what’s new','Miss Patty','“I don’t gossip. Bears simply tell me things.”'],['Have a quiet coffee','Miss Patty','She leaves a warm mug at your place and lets you enjoy the window.'],['Let Harold work','Harold','“Thank you. Somebody understands office hours.”']]},
 harmony:{title:'No audition required',duration:20,camera:670,lines:[[2,'Robin','Let’s take it from the chorus.'],[7,'Harmony Hall','A cub sways. Then another bear joins in.'],[13,'Robin','You can sing, hum, or just listen.'],[18,'Harmony Hall','The last note lingers. Nobody announces a winner.']],choices:[['Hum along','Robin','She smiles and gives you room in the chorus.'],['Applaud','Harmony Hall','A warm little wave of applause fills the room.'],['Simply listen','Harmony Hall','That is enough. The music keeps going.']]},
 bridgeview:{title:'Big Mama’s porch radar',duration:18,camera:450,lines:[[2,'Big Mama','WHO YOUR MAMA?'],[6,'Cub','I’m just going to the park!'],[10,'Big Mama','Then why you headed toward them woods?'],[14,'Big Mama','Come on up here and pull up a paw.']],choices:[['Pull up a paw','Big Mama','“You hungry? Of course you hungry.”'],['Tell her about town','Big Mama','She already knows half of it. She lets you tell it anyway.'],['Enjoy the porch','Bridgeview','The chair rocks. The breeze moves on. Nothing is required.']]}
};
function start(force=false){const active=world.querySelector('.pw-scene:not([hidden])');if(active?.dataset.scene)location=active.dataset.scene;if(!stories[location]){setDialogue('Honeybrook','Ordinary life is enough here. Try the café, bakery, porch, home, Welcome House, Harmony Hall or Northern Edge for a staged moment.');return}current=stories[location];elapsed=0;lastLine=-1;seenScene.add(location);beat=0;choices.hidden=true;choices.replaceChildren();document.querySelector('#hbStoryStop').hidden=false;document.querySelector('#hbStoryLabel').textContent=current.title;world.dataset.story='playing';}
function stop(){current=null;choices.hidden=true;document.querySelector('#hbStoryStop').hidden=true;world.dataset.story='wandering';idle=0;document.querySelector('#hbStoryLabel').textContent='Keep wandering, or just stay awhile.';}
function finish(){const key=location;if(!memory.witnessed.includes(key))memory.witnessed.push(key);save();world.dataset.story='choice';choices.replaceChildren();for(const [label,who,response] of current.choices){const button=document.createElement('button');button.textContent=label;button.onclick=()=>{memory.choices.push({scene:key,choice:label});memory.choices=memory.choices.slice(-60);save();if(key==='woodsedge'&&label==='Record what you saw')window.HBWorld?.recordObservation('Three tones and a distant roof-like shape observed. Source, location and identity remain unconfirmed.');stop();setDialogue(who,response);if(['Sit with the cubs','Have a quiet coffee','Pull up a paw'].includes(label))window.HBWorld?.sit();if(key==='woodsedge'&&label==='Return to town')document.querySelector('[data-pwjump="mainstreet"]')?.click();};choices.append(button)}const quiet=document.createElement('small');quiet.textContent='Every choice is optional. You can leave or keep watching.';choices.append(quiet);choices.hidden=false;}
function update(dt,scene){if(scene!==location){location=scene;stop()}idle+=dt;if(!current&&autoplay&&!motion.matches&&!seenScene.has(scene)&&idle>7&&stories[scene]&&!world.querySelector('.pw-choices:not([hidden])')){seenScene.add(scene);start()}if(!current)return;const old=elapsed;elapsed=Math.min(elapsed+dt,current.duration);if(elapsed<current.duration){for(let i=0;i<current.lines.length;i++)if(elapsed>=current.lines[i][0]&&i>lastLine){lastLine=i;setDialogue(current.lines[i][1],current.lines[i][2]);}}if(old<current.duration&&elapsed>=current.duration)finish();}
function actor(api,x,y,size,fur,shirt,state,name,phase=0){api.bear(x,y,size,fur,shirt,state,phase,name)}
function draw(api){if(!current)return;const {rect,ellipse,line,text,tone}=api,t=elapsed,walk=t<6?'walk':'idle';
if(location==='bakery'){const x=720-Math.min(t/6,1)*165;actor(api,x,485,1,'#b98b60','#f0d4b0',t<6?'walk':t<11?'react':t<15?'work':'talk','Wally');rect(x-52,435,106,9,'#aa8457',4);for(let i=0;i<5;i++){let px=x-40+i*19,py=422;if(t>7&&i>2){const fall=Math.min((t-7)*90,95);px+=Math.min(t-7,2)*25;py+=fall;rect(px-9,py,18,13,'#b17b56',3);ellipse(px,py-3,13,9,'#f5d7b0')}else{rect(px-8,py,16,13,'#b17b56',3);ellipse(px,py-3,12,9,'#f5d7b0')}}}
if(location==='hearthwell'){const buddyX=900-Math.min(Math.max(t-7,0)/5,1)*260;actor(api,buddyX,490,1,'#b69577','#74866e',t>7&&t<12?'walk':t>12?'work':'idle','Buddy');actor(api,435,485,.68,'#bd9166','#9b7da7',t<10?'talk':'react','Lance',2);actor(api,550,488,.68,'#c5a581','#8c9aaa',t<10?'react':'sit','Landis',3);const cx=t<12?470+Math.sin(t*3)*36:640;rect(cx,443,43,21,'#44464b',7);ellipse(cx+10,453,3,3,'#a7c5b7');ellipse(cx+32,453,3,3,'#e0ad7f');}
if(location==='welcomehouse'){rect(110,430,160,75,'#698c8c',10);rect(120,395,120,55,'#ddb68b',12);rect(138,404,43,28,'#9fc6cc',4);ellipse(143,509,18,18,'#4c493e');ellipse(239,509,18,18,'#4c493e');const x=270+Math.min(t/9,1)*230;actor(api,x,498,.9,'#b98a62','#6e9595',t<9?'walk':'talk','Toby');actor(api,365,520,.85,'#c6a080','#947e95',t<6?'idle':'talk','Papa Newberry');actor(api,610,510,.6,'#d8ba91','#bf8f93',t>13?'react':'idle','Bella');actor(api,720,510,.88,'#ab957f','#838967','sit','Grandpa');rect(x-23,433,46,43,'#b99569',4);line(x,433,x,475,'#e2c69b',4);}
if(location==='woodsedge'){actor(api,245+Math.min(t/5,1)*90,500,.9,'#b98a64','#9a7f9a',t<5?'walk':t<12?'react':'idle','Jonesha');if(t>8&&t<16){for(let i=0;i<3;i++){const r=((t-8)*35+i*28)%180;circularRipple(ellipse,620,482,r)}if(Math.floor(t*10)===90||Math.floor(t*10)===103||Math.floor(t*10)===116){/* Tone scheduling is handled at the beat boundary below. */}}if(t>15&&t<20){const alpha=Math.sin((t-15)/5*Math.PI);api.c.save();api.c.globalAlpha=alpha*.65;rect(795,267,85,63,'#c4b295',4);api.c.fillStyle='#796a63';api.c.beginPath();api.c.moveTo(780,269);api.c.lineTo(840,224);api.c.lineTo(895,269);api.c.fill();rect(824,291,20,21,'#f4d69a');api.c.restore();}for(let i=0;i<5;i++)ellipse(420+i*90+Math.sin(t*.4+i)*45,385+i*15,140,20,'#d7e5da20');}
if(location==='cafe'){const x=150+Math.min(t/9,1)*390;actor(api,x,500,.9,'#b49372','#6b879a',t<9?'walk':t<15?'talk':'sit','Harold');actor(api,745,478,1,'#dcc8a6','#758e7d',t<12?'work':'talk','Miss Patty');rect(x-28,448,28,14,'#f6e9cb',3);if(t>12){const px=740-Math.min((t-12)/3,1)*190;ellipse(px,405,32,12,'#f8dcaa');ellipse(px,401,27,9,'#b28656');}}
if(location==='harmony'){actor(api,720,480,1,'#b28462','#b06880','talk','Robin');actor(api,450,492,.7,'#b69577','#74866e',t>5?'react':'sit','Listener');actor(api,575,510,.6,'#d2ac83','#8a99b2',t>5?'react':'sit','Cub');for(let i=0;i<4;i++){const y=300-(t*20+i*33)%140;text('♪',710+Math.sin(t+i)*50,y,25,'#ffdb90')}line(760,366,760,473,'#655d51',4);ellipse(760,367,7,10,'#cbbfa2');}
if(location==='bridgeview'){actor(api,440,460,1,'#926c4f','#b17387',t<5?'react':'sit','Big Mama');const x=850-Math.min(t/9,1)*280;actor(api,x,540,.6,'#c4a27c','#a18b64',t<8?'walk':'react','Cub');rect(400,453,80,11,'#785d45',4);line(408,452,398+Math.sin(t)*4,485,'#785d45',5);line(470,452,483+Math.sin(t)*4,485,'#785d45',5);}
}
function circularRipple(ellipse,x,y,r){ellipse(x,y,r,r*.22,'#d5f0d51b')}
let beat=0;
function sounds(api){if(!current){beat=0;return}const b=Math.floor(elapsed);if(b===beat)return;beat=b;if(location==='woodsedge'&&[9,10,11].includes(b))api.tone([330,392,440][b-9],.7);if(location==='harmony'&&[5,8,11,14,17].includes(b))api.tone([392,440,494,523,392][[5,8,11,14,17].indexOf(b)],.5);if(location==='bakery'&&b===8)api.tone(130,.12);}
document.querySelector('#hbWatch').onclick=()=>start(true);document.querySelector('#hbStoryStop').onclick=stop;
function drawAuto(){const b=document.querySelector('#hbAutoScenes');b.textContent=autoplay?'Living scenes on':'Living scenes quiet';b.setAttribute('aria-pressed',String(autoplay))}drawAuto();document.querySelector('#hbAutoScenes').onclick=()=>{autoplay=!autoplay;save();drawAuto();if(!autoplay)stop()};
world.addEventListener('click',e=>{if(e.target.closest('#pwTalkPatty,#pwTalkWally,#pwTalkBigMama,#pwListenWoods,#pwWelcomeMoment,#pwHomeMoment,#pwHarmonyMoment,#pwLibraryMoment,#hbSit'))stop();});
const journal=document.createElement('dialog');journal.className='hb-notes';world.append(journal);document.querySelector('#hbStoryMemory').onclick=()=>{journal.replaceChildren();const h=document.createElement('h2');h.textContent='Your Honeybrook memories';journal.append(h);const intro=document.createElement('p');intro.textContent='A little record of days in town. No checklist, streak or obligation.';journal.append(intro);for(const place of memory.witnessed){const p=document.createElement('p');p.textContent=stories[place]?.title||place;journal.append(p)}for(const choice of memory.choices.slice(-8)){const p=document.createElement('p');p.textContent=(stories[choice.scene]?.title||choice.scene)+' — '+choice.choice;journal.append(p)}if(!memory.witnessed.length){const p=document.createElement('p');p.textContent='Quiet visits count too. Stay wherever you feel comfortable.';journal.append(p)}const close=document.createElement('button');close.textContent='Back to Honeybrook';close.onclick=()=>journal.close();journal.append(close);journal.showModal()};
window.HBStory={update,draw,sounds,active:()=>!!current,camera:()=>current?{x:current.camera,zoom:motion.matches?1:1.08}:null};
})();
