const {chromium}=await import(process.env.PLAYWRIGHT_MODULE || 'playwright');import assert from 'node:assert/strict';
const base=process.env.TEST_URL || 'http://127.0.0.1:8792';
const browser=await chromium.launch({...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{}),args:['--no-sandbox']});const key='honeybrook_craft_fair_save_v1';
try{for(const width of [1440,390]){
 const c=await browser.newContext({viewport:{width,height:1000},timezoneId:'America/Chicago'}),p=await c.newPage(),errors=[],saveRequests=[];p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>{if(r.url().includes('/api/save'))saveRequests.push(r.url())});
 await p.goto(base);await p.locator('.hb-entry-buttons [data-frontgo="connectedTown"]').click();await p.locator('#hbPlayableWorld').scrollIntoViewIfNeeded();await p.waitForTimeout(250);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));assert.equal(await p.locator('.hb-walk-hud').evaluate(e=>getComputedStyle(e).position),'static');assert.ok((await p.locator('.hb-world-art').boundingBox()).height>200);
 const canvas=p.locator('.hb-walk-canvas');await canvas.focus();await p.keyboard.down('ArrowRight');await p.waitForTimeout(300);await p.keyboard.up('ArrowRight');const first=await p.evaluate(()=>JSON.parse(localStorage.getItem('honeybrook_walk_memory_v1')));assert.ok(first.x>.5);await p.reload();await p.locator('.hb-entry-buttons [data-frontgo="connectedTown"]').click();await canvas.focus();await p.keyboard.down('ArrowRight');await p.waitForTimeout(150);await p.evaluate(()=>dispatchEvent(new Event('blur')));const stopped=await p.evaluate(()=>JSON.parse(localStorage.getItem('honeybrook_walk_memory_v1')));await p.waitForTimeout(300);await p.keyboard.up('ArrowRight');const later=await p.evaluate(()=>JSON.parse(localStorage.getItem('honeybrook_walk_memory_v1')));assert.ok(Math.abs(later.x-stopped.x)<.0001,'blur stops walking');
 await p.locator('.hb-world-rail [data-hb-tool="places"]').focus();await p.keyboard.press('Enter');await p.locator('#hbWorldDialog').waitFor({state:'visible'});assert.ok((await p.locator('#hbWorldDialogTitle').textContent()).includes('Places around'));await p.locator('#hbWorldDialog [data-hb-place="school"]').click();await p.locator('#hbWorldDialog .hb-place-art').waitFor({state:'visible'});await p.waitForFunction(()=>document.querySelector('#hbWorldDialog .hb-place-art')?.complete);assert.ok(await p.locator('#hbWorldDialog .hb-place-art').evaluate(e=>e.naturalWidth>0));await p.locator('[data-hb-place-action="2"]').click();assert.ok((await p.locator('#hbPlaceActionResult').textContent()).includes('bridge from blocks'));await p.keyboard.press('Escape');await p.locator('.hb-world-rail [data-hb-tool="journal"]').click();assert.ok((await p.locator('#hbWorldDialogBody').textContent()).includes('Honeybrook School'));await p.keyboard.press('Escape');
 await p.locator('.hb-world-rail [data-hb-tool="settings"]').click();await p.locator('[data-hb-setting="large"]').click();await p.locator('[data-hb-setting="motion"]').click();assert.equal(await p.locator('[data-hb-setting="motion"]').getAttribute('aria-pressed'),'true');await p.reload();assert.ok(await p.locator('body').evaluate(e=>e.classList.contains('hb-large-text')&&e.classList.contains('hb-reduced-motion')));await p.locator('.hb-entry-buttons [data-frontgo="connectedTown"]').click();
 await p.locator('#roleBtn').focus();await p.keyboard.press('Enter');assert.equal(await p.locator('#modal .modal-card').getAttribute('role'),'dialog');await p.keyboard.press('Escape');assert.ok(await p.locator('#modal').evaluate(e=>e.classList.contains('hidden')));await p.evaluate(()=>localStorage.clear());
 await p.goto(base+'/games/honeybrook-craft-fair/');await p.locator('#player-name').fill('Temporary Bear');await p.locator('#btn-start').click();await p.locator('#modal-actions').getByRole('button',{name:'Step into the square',exact:true}).click();await p.waitForTimeout(200);let snap=await p.evaluate(k=>JSON.parse(localStorage.getItem(k)),key);assert.equal(snap.name,'Temporary Bear');assert.equal(snap.coins,20);assert.ok(await p.locator('.fair-accessible-places').isVisible());
 await p.locator('#hud-toggle').click();await p.locator('#btn-shop').click();assert.equal(await p.locator('#modal-body [data-val="rod"]').isDisabled(),true);await p.locator('#modal-actions').getByRole('button',{name:'Close',exact:true}).click();await p.locator('#hud-toggle').click();const download=p.waitForEvent('download');await p.locator('#btn-backup').click();assert.equal((await download).suggestedFilename(),'honeybrook-fair-backup.json');
 const before=await p.evaluate(k=>localStorage.getItem(k),key);await p.locator('#fair-backup-file').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({...snap,coins:-1}))});await p.waitForTimeout(100);assert.equal(await p.evaluate(k=>localStorage.getItem(k),key),before);
 // Import synthetic funding through the same backup flow a player uses.
 snap.coins=100;snap.found={...(snap.found||{}),v4:true};p.once('dialog',d=>d.accept());const reload=p.waitForEvent('load');await p.locator('#fair-backup-file').setInputFiles({name:'synthetic.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(snap))});await reload;await p.locator('#btn-continue').click();await p.waitForTimeout(150);await p.locator('#hud-toggle').click();await p.locator('#btn-shop').click();await p.locator('#modal-body [data-val="rod"]').click();await p.waitForTimeout(100);assert.ok((await p.locator('#hud-coins').textContent()).includes('55'));await p.reload();await p.locator('#btn-continue').click();await p.locator('#hud-toggle').click();await p.locator('#btn-shop').click();assert.equal(await p.locator('#modal-body [data-val="rod"]').isDisabled(),true);assert.ok((await p.locator('#modal-body [data-val="rod"]').textContent()).includes('Owned'));await p.locator('#modal-actions').getByRole('button',{name:'Close',exact:true}).click();await p.locator('.fair-accessible-places button').getByText('Wally\'s Bakery',{exact:true}).click().catch(async()=>p.locator('.fair-accessible-places button').filter({hasText:"Wally's Bakery"}).click());await p.locator('#scene-bakery.active').waitFor({state:'visible'});assert.ok((await p.locator('#recipe-card').textContent()).includes('recipe'));await p.waitForTimeout(650);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));assert.deepEqual(saveRequests,[]);assert.deepEqual(errors,[]);await p.evaluate(()=>localStorage.clear());await c.close();console.log(`PASS ${width}px: town visits/actions/journal, keyboard buttons, walking save/reload/blur stop, saved display settings, dialog Escape; Fair start/save/continue, backup export, invalid restore preserves progress, valid restore, insufficient funds, purchase balance and owned item survive reload, bakery opens, no save-server requests or runtime errors. Test storage cleared.`);
}
}finally{await browser.close()}
