const {chromium}=await import(process.env.PLAYWRIGHT_MODULE || 'playwright');import assert from 'node:assert/strict';
const b=await chromium.launch({...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{}),args:['--no-sandbox']});
try{for(const width of [1440,390]){const c=await b.newContext({viewport:{width,height:1000}}),p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(process.env.TEST_URL || 'http://127.0.0.1:8792');await p.locator('.hb-entry-buttons [data-frontgo="connectedTown"]').click();const doors=await p.locator('[data-bv],[data-ms],[data-ts],[data-cc],[data-ep],[data-fr],[data-hh],[data-ne],[data-nw],[data-os],[data-pk],[data-se],[data-sq]').evaluateAll(bs=>bs.map(b=>{const attr=[...b.attributes].find(a=>/^data-(bv|ms|ts|cc|ep|fr|hh|ne|nw|os|pk|se|sq)$/.test(a.name));return{attr:attr.name,name:attr.value}}));for(const d of doors){if(d.name==='Return to Honeybrook')continue;const door=p.locator('['+d.attr+']').filter({has:p.locator('b')}).filter({});const exact=p.locator('['+d.attr+'="'+d.name.replaceAll('"','\\"')+'"]');await exact.click();await p.locator('#destinationVisit h1').waitFor();assert.equal(await p.locator('#destinationVisit h1').textContent(),d.name);assert.equal(await p.locator('#destinationVisit').isVisible(),true);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await p.waitForFunction(()=>document.querySelector('.visit-room-photo')?.complete);assert.ok(await p.locator('.visit-room-photo').evaluate(e=>e.naturalWidth>0));await p.locator('[data-visit-back]').click();await p.locator('#destinationVisit').waitFor({state:'hidden'});}
const open=async(attr,name)=>{await p.locator('['+attr+'="'+name+'"] ').click()};
await open('data-bv','Community Garden');for(let i=0;i<3;i++)await p.locator('[data-plot="0"]').click();assert.match(await p.locator('.visit-count').textContent(),/1 crops/);await p.reload();assert.match(await p.locator('.visit-count').textContent(),/1 crops/);await p.locator('[data-visit-back]').click();await p.locator('#destinationVisit').waitFor({state:'hidden'});
await open('data-ms','The Honey Mug Café');for(let i=0;i<3;i++)await p.locator('[data-visit-action="ingredient"]').nth(i).click();await p.locator('[data-visit-action="serve"]').click();assert.match(await p.locator('.visit-count').textContent(),/1 trays/);await p.locator('[data-visit-back]').click();await p.locator('#destinationVisit').waitFor({state:'hidden'});
await open('data-ts','Honeybrook Post Office');await p.locator('[name="message"]').fill('A temporary test letter.');await p.locator('#visitLetter button').click();assert.match(await p.locator('.visit-outbox').textContent(),/temporary test/);await p.locator('[data-visit-door]').first().click();await p.goBack();assert.equal(await p.locator('#destinationVisit h1').textContent(),'Honeybrook Post Office');await p.locator('[data-visit-back]').click();await p.locator('#destinationVisit').waitFor({state:'hidden'});
await open('data-hh','Harmony Hall');await p.keyboard.press('a');assert.equal(await p.locator('.visit-staff').textContent(),'C');await p.keyboard.press('Escape');await p.locator('#destinationVisit').waitFor({state:'hidden'});
await open('data-hh',"Poppy's Art Studio");const canvas=p.locator('#visitEasel');await canvas.scrollIntoViewIfNeeded();const r=await canvas.boundingBox();await p.mouse.move(r.x+20,r.y+20);await p.mouse.down();await p.mouse.move(r.x+120,r.y+70);await p.mouse.up();assert.ok(await p.evaluate(()=>JSON.parse(localStorage.getItem('honeybrook_destination_visits_v1'))["Poppy's Art Studio"].painting));const dl=p.waitForEvent('download');await p.locator('[data-visit-action="download"]').click();assert.equal((await dl).suggestedFilename(),'honeybrook-painting.png');await p.locator('[data-visit-back]').click();await p.locator('#destinationVisit').waitFor({state:'hidden'});
await open('data-cc','Honeybrook Health Center');for(const box of await p.locator('[data-care-step]').all())await box.check();assert.match(await p.locator('.visit-count').textContent(),/station is ready/);await p.locator('[data-visit-back]').click();await p.locator('#destinationVisit').waitFor({state:'hidden'});
await open('data-sq','Honeybrook School');for(const word of ['Every','bear','belongs.'])await p.locator('[data-word="'+word+'"]').click();assert.match(await p.locator('.visit-count').textContent(),/Correct/);await p.locator('[data-visit-back]').click();await p.locator('#destinationVisit').waitFor({state:'hidden'});
await open('data-ep','Honeybrook Arcade');for(let i=0;i<5;i++)await p.locator('[data-visit-action="catch"]').click();assert.match(await p.locator('.visit-count').textContent(),/Round complete/);assert.deepEqual(errors,[]);await p.evaluate(()=>localStorage.clear());await c.close();console.log('PASS '+width+'px: '+doors.length+' district routes (78 destination views and the town return), images, return paths, no overflow; garden persistence, cafe tray, mail, neighbor navigation and browser Back, piano keyboard, painting/download, care checklist, learning puzzle, arcade. Storage cleared.');}}finally{await b.close()}
