const fs=require('fs'),vm=require('vm'),assert=require('assert');
class Node{constructor(){this.children=[];this.dataset={};this.hidden=false;this.listeners={}}append(...n){this.children.push(...n)}replaceChildren(...n){this.children=n}addEventListener(n,f){(this.listeners[n]||=[]).push(f)}}
function boot(saved={},initial='woodsedge'){const world=new Node(),scene=new Node(),dialogue=new Node(),hud=new Node(),nodes={},arrivals=[],notes=[],tones=[];scene.dataset.scene=initial;world.querySelector=s=>s.includes('pw-dialogue')?dialogue:s.includes('pw-scene')?scene:s==='.pw-hud'?hud:(nodes[s]||=new Node());const context={window:{HBStory:{stop(){}},HBActivities:{stop(){}},HBWorld:{arrive:(...p)=>arrivals.push(p),position:()=>({x:620,y:530}),recordObservation:n=>notes.push(n),sound:(...a)=>tones.push(a),seat(){},sit(){},cancelMovement(){}}},document:{querySelector:()=>world,createElement:()=>new Node()},localStorage:{getItem:k=>saved[k]||null,setItem:(k,v)=>saved[k]=v}};vm.createContext(context);vm.runInContext(fs.readFileSync(require('path').join(__dirname,'../world-woods.js'),'utf8'),context);const api=context.window.HBWoods,panel=world.children[0],choices=world.children[1];function click(label,container=panel){const b=container.children.find(x=>x.textContent===label);assert(b,'Missing action '+label);b.onclick()}function controls(){for(const f of world.listeners.click)f({target:{closest:()=>({id:'hbObjects'})},stopImmediatePropagation(){}})}return{api,world,scene,panel,choices,arrivals,notes,tones,saved,click,controls,state:()=>JSON.parse(saved.hb_northern_paths_v1||'{}')};}
const t=boot(),noop=()=>{},c=new Proxy({createLinearGradient:()=>({addColorStop:noop})},{get:(o,k)=>o[k]||noop,set:()=>true});let actors=[],hits=[],roof=[],waterCount=0;
const draw=()=>t.api.draw({c,rect:(...a)=>{if(a[0]===734)roof.push(a)},ellipse:noop,line:noop,text:noop,bear:(...a)=>actors.push(a),tree:noop,water:()=>waterCount++,hit:(...a)=>hits.push(a),night:true});
assert(!t.api.current());assert(!t.api.enter('bogus'));t.controls();t.click('Follow the path to Singing Pond');assert(!t.api.current(),'Walking precedes the path transition');t.api.update(.7,'woodsedge');assert.equal(t.api.current(),'pond');t.controls();t.click('Record an observation');assert(!t.notes[0].includes('Three tones'),'Unwatched tones cannot be recorded as observations');t.api.watch();for(let i=0;i<241;i++){t.api.update(.1,'woodsedge');draw()}assert.equal(t.world.dataset.woodsMoment,'choice');assert.equal(t.choices.children.length,3);assert(t.state().pondWatched);assert.deepEqual(t.tones.filter(x=>x[1]===.85).map(x=>x[0]),[330,392,440]);t.click('Keep the observation',t.choices);assert(t.notes.at(-1).includes('No source was visible'));
for(const [zone,duration] of [['ruins',22],['lookout',25]]){t.api.enter(zone);t.api.watch();for(let i=0;i<=duration*10;i++){t.api.update(.1,'woodsedge');draw()}assert.equal(t.choices.children.length,3);t.click('Keep the observation',t.choices);assert(t.notes.at(-1).includes('unconfirmed'));}
assert(actors.some(a=>a.includes('walk'))&&actors.some(a=>a.includes('Jonesha')));assert(waterCount>0);assert(roof.length>0,'The distant roof is actually drawn during the lookout scene');assert(hits.some(a=>a.includes('Follow trail to Northern Edge')));
// Every sublocation has a route back and no route points outside the original scene.
for(const [zone,paths] of Object.entries(t.api.routes)){assert(paths.some(([,next])=>next===null));for(const [,next] of paths)assert(next===null||t.api.routes[next]);}
t.api.enter('lookout');const reload=boot(t.saved);assert.equal(reload.api.current(),'lookout');assert.deepEqual(reload.arrivals[0],[620,530]);t.api.walkTo(null);t.api.update(.7,'woodsedge');assert(!t.api.current());t.api.enter('pond');t.scene.dataset.scene='park';t.api.update(.1,'park');assert(!t.api.current());assert.equal(t.world.dataset.woods,undefined);const bad=boot({hb_northern_paths_v1:'null'});assert(bad.api.enter('pond'));
console.log('PASS: three connected woods locations, staged visual mysteries, optional choices, three tones, evidence safeguards, roof glimpse, return paths, persistence and navigation cleanup.');
