const fs=require('fs'),vm=require('vm'),assert=require('assert');
class Node{constructor(){this.children=[];this.hidden=false;this.dataset={};}replaceChildren(...nodes){this.children=nodes}append(...nodes){this.children.push(...nodes)}setAttribute(){}addEventListener(){}}
const path=require('path').join(__dirname,'../world-activities.js');
function boot(saved={}){const nodes={},dialogue=new Node(),active=new Node(),world=new Node(),toolbar=new Node(),observations=[];let story=false;world.querySelector=s=>s==='.hb-world-tools'?toolbar:s.includes('pw-dialogue')?dialogue:active;const context={document:{querySelector:()=>world,createElement:()=>new Node()},window:{HBStory:{active:()=>story,stop:()=>story=false},HBWorld:{sit(){},sound(){},recordObservation:x=>observations.push(x)}},localStorage:{getItem:k=>saved[k]||null,setItem:(k,v)=>saved[k]=v}};vm.createContext(context);vm.runInContext(fs.readFileSync(path,'utf8'),context);const panel=world.children[0],open=toolbar.children[0],api=context.window.HBActivities;function scene(name){active.dataset.scene=name;api.update(.01,name)}function click(name){const b=panel.children.find(x=>x.textContent===name);assert(b,'Missing action: '+name);b.onclick()}function choose(name,label){scene(name);open.onclick();click(label)}return {api,panel,scene,click,choose,observations,state:()=>JSON.parse(saved.hb_little_activities_v1||'{}'),saved,story:v=>story=v};}
const t=boot();t.choose('cafe','Make a warm drink');t.click('Pour into the mug');assert(!t.state().tea,'Out of order pouring must not finish a drink');for(const x of ['Warm the kettle','Add the tea','Pour into the mug'])t.click(x);assert(t.state().tea);t.click('Back to wandering');
t.choose('bakery','Decorate cupcakes');t.click('Berry frosting');t.click('Decorate cupcake 1');t.click('Honey frosting');t.click('Decorate cupcake 2');t.click('Rose frosting');t.click('Decorate cupcake 3');assert.deepEqual(t.state().cupcakes,['berry','honey','rose']);
t.choose('park','Visit the little garden');t.click('Water the flowers');assert.equal(t.state().garden,0);t.click('Plant a seed');assert.equal(t.state().garden,1);t.click('Water the flowers');assert.equal(t.state().garden,2);
t.choose('mainstreet','Visit the mailbox');t.click('Leave it in the mailbox');assert(!t.state().mail);for(const x of ['Choose a welcome note','Fold the envelope','Leave it in the mailbox'])t.click(x);assert(t.state().mail);
t.choose('library','Examine the torn map');for(const [i,n] of [[1,3],[2,2],[3,1],[4,3]])for(let j=0;j<n;j++)t.click('Rotate fragment '+i);assert(t.state().mapAligned);assert(t.observations[0].includes('unknown'));
t.scene('cozy');assert(!t.api.active());assert(t.panel.hidden);const reloaded=boot(t.saved);assert.deepEqual(reloaded.state().cupcakes,['berry','honey','rose']);assert(reloaded.state().tea&&reloaded.state().garden===2&&reloaded.state().mail);reloaded.choose('cafe','Make a warm drink');reloaded.story(true);reloaded.api.update(.05,'cafe');assert(!reloaded.api.active());
const broken=boot({hb_little_activities_v1:'null'});broken.choose('park','Visit the little garden');broken.click('Plant a seed');assert.equal(broken.state().garden,1);console.log('PASS: five activities, order guards, saved visible changes, map evidence, scene cleanup and invalid save recovery.');
