const fs=require('fs'),vm=require('vm'),assert=require('assert');
class Node{constructor(){this.listeners={};this.dataset={};this.hidden=false;this.children=[];this.clientWidth=1000;this.clientHeight=650;this.clicks=0}setAttribute(){}append(...x){this.children.push(...x)}prepend(...x){this.children.unshift(...x)}after(){}replaceChildren(...x){this.children=x}addEventListener(n,fn){this.listeners[n]=fn}click(){this.clicks++;this.onclick?.({currentTarget:this})}focus(){}getBoundingClientRect(){return {left:0,top:0,width:this.clientWidth,height:this.clientHeight}}getContext(){return ctx}}
let transform;const noop=()=>{},ctx=new Proxy({setTransform:(...x)=>transform=x,createLinearGradient:()=>({addColorStop:noop})},{get:(o,k)=>k in o?o[k]:noop,set:(o,k,v)=>(o[k]=v,true)});
const nodes={},world=new Node(),scenes=['mainstreet','cafe','bakery','woodsedge','bridgeview','park','bridge','townsquare','library','tech','games','harmony','hearthwell','cozy','welcomehouse'].map((name,i)=>Object.assign(new Node(),{dataset:{scene:name},hidden:i!==0}));const get=s=>nodes[s]||=new Node();world.querySelectorAll=()=>scenes;world.querySelector=s=>s.includes('pw-dialogue')?get(s):s.startsWith('.pw-scene:not')?scenes.find(x=>!x.hidden):get(s);const saved={},timers=[];let raf,observe,interval,canvas;
const context={console,document:{hidden:false,querySelector:s=>s==='#playableWorld'?world:get(s),createElement:t=>{const n=new Node();if(t==='canvas')canvas=n;return n},addEventListener:noop},window:{matchMedia:()=>({matches:false}),devicePixelRatio:1,addEventListener:noop},localStorage:{getItem:k=>saved[k]||null,setItem:(k,v)=>saved[k]=v},MutationObserver:class{constructor(fn){observe=fn}observe(){}},requestAnimationFrame:fn=>raf=fn,setTimeout:fn=>timers.push(fn),setInterval:fn=>interval=fn,queueMicrotask:fn=>fn()};
vm.createContext(context);vm.runInContext(fs.readFileSync(require('path').join(__dirname,'../world-life.js'),'utf8'),context);vm.runInContext(fs.readFileSync(require('path').join(__dirname,'../world-renderer.js'),'utf8'),context);
let clock=0;function frames(n){for(let i=0;i<n;i++)raf(clock+=1000/60)}frames(2);
const cafe=get('[data-pwjump="cafe"]');canvas.listeners.pointerdown({clientX:185,clientY:320});assert.equal(cafe.clicks,0,'A distant door should not teleport the bear');frames(160);assert(timers.length,'Walking to the door starts a transition');timers.shift()();assert.equal(cafe.clicks,1);
for(const next of scenes){scenes.forEach(x=>x.hidden=x!==next);observe();frames(2);assert.equal(world.dataset.illustrated,next.dataset.scene);}
scenes.forEach(x=>x.hidden=x.dataset.scene!=='mainstreet');observe();frames(2);canvas.listeners.pointerdown({clientX:940,clientY:584});frames(20);interval();const position=JSON.parse(saved.hb_illustrated_world_v1).position;assert(position.x>500&&position.x<940,'Path walking advances smoothly');
canvas.listeners.pointerdown({clientX:185,clientY:320});scenes.forEach(x=>x.hidden=x.dataset.scene!=='park');observe();const count=timers.length;frames(180);assert.equal(timers.length,count,'A scene change cancels an old pending interaction');
for(let i=0;i<4;i++)get('#hbLight').onclick();assert.equal(get('#hbLight').textContent,'Time: cycle');for(let i=0;i<2;i++)get('#hbWeather').onclick();assert.equal(get('#hbWeather').textContent,'Weather: mist');frames(10);
canvas.clientWidth=375;canvas.clientHeight=600;frames(2);assert.equal(canvas.width,375);assert.equal(canvas.height,600);assert(Math.abs(transform[0]-transform[3])<.001,'Mobile camera must use uniform scale so bears are not stretched');canvas.listeners.pointerdown({clientX:187.5,clientY:520});frames(90);interval();const mobile=JSON.parse(saved.hb_illustrated_world_v1).position;assert(mobile.x>=60&&mobile.x<=940&&mobile.y>=475&&mobile.y<=585);
canvas.clientWidth=1000;canvas.clientHeight=650;scenes.forEach(x=>x.hidden=x.dataset.scene!=='welcomehouse');observe();frames(90);vm.runInContext(fs.readFileSync(require('path').join(__dirname,'../world-rooms.js'),'utf8'),context);timers.length=0;canvas.listeners.pointerdown({clientX:500,clientY:380});frames(210);assert(timers.length,'The Welcome House exterior has an enterable door');timers.shift()();assert.equal(context.window.HBRooms.current(),'newberry','Exterior door dispatches to the new interior');frames(90);assert(context.window.HBWorld.useObject('Enter Kitchen'));assert.equal(context.window.HBRooms.current(),'newberry','Interior travel first walks to the door');frames(360);assert.equal(context.window.HBRooms.current(),'newberry-kitchen');frames(90);assert(context.window.HBWorld.useObject('Enter Porch'));frames(360);assert(!context.window.HBRooms.current(),'The kitchen porch door leads outside');context.window.HBRooms.leave();frames(10);assert(!context.window.HBRooms.current());
scenes.forEach(x=>x.hidden=x.dataset.scene!=='mainstreet');observe();frames(90);context.window.HBWorld.arrive(500,550);frames(60);canvas.listeners.pointerdown({clientX:940,clientY:585});for(let i=0;i<4;i++)raf(clock+=500);interval();const slower=JSON.parse(saved.hb_illustrated_world_v1).position;assert(slower.x>795,'Low frame rates must not slow walking speed');
console.log('PASS: physical door approach, smooth walking, pending interaction cancellation, all scene draws, portrait mobile scale, weather, cycling time and the enterable Newberry house.');
scenes.forEach(x=>x.hidden=x.dataset.scene!=='hearthwell');observe();frames(3);assert.equal(context.window.HBRooms.current(),'hearthwell-living');frames(90);assert(context.window.HBWorld.useObject('Join the family sofa'));frames(240);const seated=context.window.HBWorld.position();assert(Math.abs(seated.x-557)<2&&Math.abs(seated.y-449)<2,'The player physically arrives at the sofa seat');
assert(context.window.HBWorld.useObject('Enter Kitchen'));frames(300);assert.equal(context.window.HBRooms.current(),'hearthwell-kitchen');frames(90);assert(context.window.HBWorld.useObject('Enter Porch'));frames(360);assert(!context.window.HBRooms.current());assert(get('[data-pwjump="bridgeview"]').clicks>0,'The Hearthwell porch returns to Bridgeview');
console.log('PASS: Hearthwell physical sofa seating, connected kitchen door and porch return to Bridgeview.');
