const fs=require('fs'),vm=require('vm'),assert=require('assert'),path=require('path').join(__dirname,'../world-rooms.js');
class Node{constructor(){this.children=[];this.hidden=false;this.dataset={};this.listeners={}}append(...x){this.children.push(...x)}replaceChildren(...x){this.children=x}setAttribute(){}addEventListener(n,fn){(this.listeners[n]||=[]).push(fn)}}
function boot(saved={},initialScene='welcomehouse'){const world=new Node(),scene=new Node(),dialogue=new Node(),hud=new Node(),nodes={},arrivals=[];scene.dataset.scene=initialScene;world.querySelector=s=>s==='dialog[open]'?null:s.includes('pw-dialogue')?dialogue:s.includes('pw-scene')?scene:s==='.pw-hud'?hud:(nodes[s]||=new Node());let stopped=0;const context={window:{HBStory:{stop(){stopped++}},HBActivities:{stop(){}},HBWorld:{position:()=>({x:740,y:530}),arrive:(...p)=>arrivals.push(p),sound(){},sit(){}}},document:{querySelector:()=>world,createElement:()=>new Node()},localStorage:{getItem:k=>saved[k]||null,setItem:(k,v)=>saved[k]=v}};vm.createContext(context);vm.runInContext(fs.readFileSync(path,'utf8'),context);const api=context.window.HBRooms,panel=world.children[0],choices=world.children[1],leave=hud.children[0];function click(label,container=panel){const b=container.children.find(x=>x.textContent===label);assert(b,'Missing room action '+label);b.onclick()}function controls(){const b={id:'hbObjects'};for(const f of world.listeners.click||[])f({target:{closest:()=>b},stopImmediatePropagation(){}})}return {api,world,panel,choices,scene,leave,controls,click,arrivals,saved,state:()=>JSON.parse(saved.hb_newberry_home_v1||'{}'),stopped:()=>stopped};}
const t=boot();assert(!t.api.current());assert(!t.api.enter('unknown'));assert(t.api.enter('newberry'));assert(t.stopped());assert.equal(t.world.dataset.room,'newberry');t.controls();t.click('Choose the curtains');t.click('Sage curtains');assert.equal(t.state().curtain,'sage');t.controls();t.click('Put the family photo on the mantel');assert(t.state().photo);t.controls();t.click('Visit the kitchen');assert.equal(t.api.current(),'newberry','Door animation precedes entering');t.api.update(.71,'welcomehouse');assert.equal(t.api.current(),'newberry-kitchen');t.controls();t.click('Make a little welcome snack');t.click('Set out the plate');assert(!t.state().snack);for(const label of ['Slice the bread','Spread the berry jam','Set out the plate'])t.click(label);assert(t.state().snack);t.click('Take it to the family');t.api.update(.71,'welcomehouse');assert.equal(t.api.current(),'newberry');t.controls();t.click('Visit Bella’s nook');t.api.update(.71,'welcomehouse');assert.equal(t.api.current(),'bella-nook');
const colors=[],bears=[],hits=[],noop=()=>{},canvas=new Proxy({},{get:()=>noop,set:()=>true});const draw=()=>t.api.draw({c:canvas,rect:(...x)=>colors.push(x[4]),ellipse:noop,line:noop,text:noop,hit:(...x)=>hits.push(x),bear:(...x)=>bears.push(x),tree:noop,night:false});
for(const [room,film,duration] of [['newberry','family',21],['newberry-kitchen','kettle',17],['bella-nook','reading',20],['newberry','mail',16]]){t.api.enter(room);t.api.watch(film);for(let i=0;i<duration*20+1;i++){t.api.update(.05,'welcomehouse');draw()}assert.equal(t.world.dataset.roomMoment,'choice');assert.equal(t.choices.children.length,3);assert(t.state()[film+'Watched']);t.api.stop();}
assert(colors.includes('#82997c'),'Saved curtain color is rendered');assert(bears.some(x=>x.includes('Bella')));assert(bears.some(x=>x.includes('Papa Newberry')));assert(hits.length>0);
t.api.enter('newberry');const reload=boot(t.saved);assert.equal(reload.api.current(),'newberry');assert.deepEqual(reload.arrivals[0],[740,530],'Reload restores the player position inside the room');assert(reload.state().snack&&reload.state().photo);reload.leave.onclick();reload.api.update(.71,'welcomehouse');assert(!reload.api.current());assert.equal(reload.world.dataset.room,undefined);t.scene.dataset.scene='park';t.api.update(.1,'park');assert(!t.api.current(),'Town navigation closes the interior');const invalid=boot({hb_newberry_home_v1:'null'});invalid.api.enter('newberry');assert.equal(invalid.state().curtain,'honey');
console.log('PASS: three enterable rooms, animated transitions and exits, four family films, optional snack ordering, visible persistent décor and room restoration.');
// The original Hearthwell village location expands in place, with no replacement graph.
const h=boot();h.scene.dataset.scene='hearthwell';h.api.update(.1,'hearthwell');assert.equal(h.api.current(),'hearthwell-living');assert(!h.api.enter('newberry'),'Homes cannot be entered from an unrelated village scene');
h.controls();h.click('Visit Buddy’s kitchen');assert.equal(h.api.current(),'hearthwell-living');h.api.update(.71,'hearthwell');assert.equal(h.api.current(),'hearthwell-kitchen');
let hearthHits=[],hearthActors=[];const hearthDraw=()=>h.api.draw({c:canvas,rect:noop,ellipse:noop,line:noop,text:noop,hit:(...x)=>hearthHits.push(x),bear:(...x)=>hearthActors.push(x),tree:noop,night:false});
for(const [r,film,duration] of [['hearthwell-living','controllers',22],['hearthwell-kitchen','supper',20],['hearthwell-music','singalong',21]]){h.api.enter(r);h.api.watch(film);for(let i=0;i<=duration*10;i++){h.api.update(.1,'hearthwell');hearthDraw()}assert.equal(h.world.dataset.roomMoment,'choice');assert.equal(h.choices.children.length,3);assert(h.state()[film+'Watched']);h.api.stop()}
assert(h.state().supper,'The supper scene leaves plates on the table');assert(hearthActors.some(x=>x.includes('Buddy'))&&hearthActors.some(x=>x.includes('Lance'))&&hearthActors.some(x=>x.includes('Landis')));assert(hearthHits.some(x=>x.includes('Enter Porch')));
h.api.enter('hearthwell-music');h.controls();h.click('Play a few piano notes');for(const label of ['C','E','G','A'])h.click(label);assert.deepEqual(h.state().familyTune,[0,2,3,4]);h.click('Play our saved tune');h.api.update(.7,'hearthwell');h.api.stop();h.api.update(3,'hearthwell');assert.equal(h.world.dataset.roomMoment,'wandering','Stopping music cancels replay');
h.api.enter('hearthwell-living');h.controls();h.click('Turn the reading lamp off');assert.equal(h.state().familyLamp,false);h.scene.dataset.scene='park';h.api.update(.1,'park');assert(!h.api.current());h.scene.dataset.scene='hearthwell';h.api.update(.1,'hearthwell');assert.equal(h.api.current(),'hearthwell-living');
console.log('PASS: Hearthwell rooms, three family movies, visible supper, optional melody memory, lamp state and village navigation cleanup.');

const restoredFamily=boot({...h.saved,hb_newberry_home_v1:JSON.stringify({...h.state(),room:'hearthwell-music',scene:'hearthwell'})},'hearthwell');assert.equal(restoredFamily.api.current(),'hearthwell-music');assert.deepEqual(restoredFamily.state().familyTune,[0,2,3,4]);assert.equal(restoredFamily.state().familyLamp,false);assert.deepEqual(restoredFamily.arrivals[0],[740,530]);console.log('PASS: saved Hearthwell room, tune, lamp and exact player position restore together.');
