const fs=require('fs'),vm=require('vm'),assert=require('assert');
class Node{constructor(){this.listeners={};this.dataset={};this.hidden=false;this.children=[];this.clientWidth=1000;this.clientHeight=650;this.clicks=0}setAttribute(){}append(...x){this.children.push(...x)}prepend(...x){this.children.unshift(...x)}after(){}replaceChildren(...x){this.children=x}addEventListener(n,fn){this.listeners[n]=fn}click(){this.clicks++;this.onclick?.({currentTarget:this})}focus(){}getBoundingClientRect(){return {left:0,top:0,width:1000,height:650}}getContext(){return ctx}}
const noop=()=>{},ctx=new Proxy({createLinearGradient:()=>({addColorStop:noop})},{get:(o,k)=>k in o?o[k]:noop,set:(o,k,v)=>(o[k]=v,true)});
const nodes={},world=new Node(),scenes=['mainstreet','cafe','bakery','woodsedge','bridgeview','park','bridge','townsquare','library','tech','games','harmony','hearthwell','cozy','welcomehouse'].map((name,i)=>Object.assign(new Node(),{dataset:{scene:name},hidden:i!==0}));const get=s=>nodes[s]||=new Node();world.querySelectorAll=()=>scenes;world.querySelector=s=>get(s);const saved={},timers=[];let raf,observe,interval,canvas;
const context={console,document:{hidden:false,querySelector:s=>s==='#playableWorld'?world:get(s),createElement:t=>{const n=new Node();if(t==='canvas')canvas=n;return n},addEventListener:noop},window:{matchMedia:()=>({matches:false}),devicePixelRatio:1,addEventListener:noop},localStorage:{getItem:k=>saved[k]||null,setItem:(k,v)=>saved[k]=v},MutationObserver:class{constructor(fn){observe=fn}observe(){}},requestAnimationFrame:fn=>raf=fn,setTimeout:fn=>timers.push(fn),setInterval:fn=>interval=fn,queueMicrotask:fn=>fn()};
vm.createContext(context);vm.runInContext(fs.readFileSync(require('path').join(__dirname,'../world-life.js'),'utf8'),context);vm.runInContext(fs.readFileSync(require('path').join(__dirname,'../world-renderer.js'),'utf8'),context);
let clock=0;function frames(n){for(let i=0;i<n;i++)raf(clock+=1000/60)}frames(2);
const cafe=get('[data-pwjump="cafe"]');canvas.listeners.pointerdown({clientX:185,clientY:320});assert.equal(cafe.clicks,0,'A distant door should not teleport the bear');frames(160);assert(timers.length,'Walking to the door starts a transition');timers.shift()();assert.equal(cafe.clicks,1);
for(const next of scenes){scenes.forEach(x=>x.hidden=x!==next);observe();frames(2);assert.equal(world.dataset.illustrated,next.dataset.scene);}
scenes.forEach(x=>x.hidden=x.dataset.scene!=='mainstreet');observe();frames(2);canvas.listeners.pointerdown({clientX:940,clientY:584});frames(20);interval();const position=JSON.parse(saved.hb_illustrated_world_v1).position;assert(position.x>500&&position.x<940,'Path walking advances smoothly');
canvas.listeners.pointerdown({clientX:185,clientY:320});scenes.forEach(x=>x.hidden=x.dataset.scene!=='park');observe();const count=timers.length;frames(180);assert.equal(timers.length,count,'A scene change cancels an old pending interaction');
for(let i=0;i<4;i++)get('#hbLight').onclick();assert.equal(get('#hbLight').textContent,'Time: cycle');for(let i=0;i<2;i++)get('#hbWeather').onclick();assert.equal(get('#hbWeather').textContent,'Weather: mist');frames(10);
console.log('PASS: physical door approach, smooth walking, pending interaction cancellation, all scene draws, weather and cycling time.');
